name: "Build patched"

on:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: "windows-2022"
    env:
      CARGO_INCREMENTAL: "0"
      SCCACHE_GHA_ENABLED: "true"
      RUSTC_WRAPPER: "sccache"
      RUSTUP_WINDOWS_PATH_ADD_BIN: "1"

    steps:
      - name: "checkout repo"
        uses: actions/checkout@v4
        with:
          submodules: "recursive"
      - name: "Install Rust"
        uses: dtolnay/rust-toolchain@stable
        with:
          target: "x86_64-pc-windows-msvc"
      - name: "Compile with sccache"
        uses: mozilla-actions/sccache-action@v0.0.9
      - name: "Cache Rust Dependencies"
        uses: actions/cache@v4
        id: cache-cargo-vendor
        with:
          path: |
            vendor
            .cargo/config
          key: "cargo-deps-${{ hashFiles('**/Cargo.lock') }}"
      - name: "Vendor dependecies"
        if: steps.cache-cargo-vendor.outputs.cache-hit != 'true'
        shell: bash
        run: "cargo vendor --locked --versioned-dirs >> .cargo/config"
      - name: "Build wezterm (Release mode)"
        shell: cmd
        run: |
          PATH C:\Strawberry\perl\bin;%PATH%
          cargo build -p wezterm --release
      - name: "Build wezterm-gui (Release mode)"
        shell: cmd
        run: |
          PATH C:\Strawberry\perl\bin;%PATH%
          cargo build -p wezterm-gui --release
      - name: "Build wezterm-mux-server (Release mode)"
        shell: cmd
        run: |
          PATH C:\Strawberry\perl\bin;%PATH%
          cargo build -p wezterm-mux-server --release
      - name: "Build strip-ansi-escapes (Release mode)"
        shell: cmd
        run: |
          PATH C:\Strawberry\perl\bin;%PATH%
          cargo build -p strip-ansi-escapes --release
      - name: "Package"
        shell: bash
        run: "bash ci/deploy.sh"
      - name: "Upload artifact"
        uses: actions/upload-artifact@v4
        with:
          name: "patched-windows"
          path: |
            WezTerm-*.zip
            WezTerm-*.exe
          retention-days: 30

  build-ubuntu:
    runs-on: "ubuntu-latest"
    container: "ubuntu:22.04"
    env:
      CARGO_INCREMENTAL: "0"
      SCCACHE_GHA_ENABLED: "true"
      RUSTC_WRAPPER: "sccache"

    steps:
      - name: "set APT to non-interactive"
        shell: bash
        run: "echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections"
      - name: "Update APT"
        shell: bash
        run: "apt update"
      - name: "Install git"
        shell: bash
        run: "apt-get install -y git"
      - name: "Install curl"
        shell: bash
        run: "apt-get install -y curl"
      - name: "Workaround git permissions issue"
        shell: bash
        run: "git config --global --add safe.directory /__w/wezterm/wezterm"
      - name: "checkout repo"
        uses: actions/checkout@v4
        with:
          submodules: "recursive"
      - name: "Install Rust"
        uses: dtolnay/rust-toolchain@stable
      - name: "Compile with sccache"
        uses: mozilla-actions/sccache-action@v0.0.9
      - name: "Cache Rust Dependencies"
        uses: actions/cache@v4
        id: cache-cargo-vendor
        with:
          path: |
            vendor
            .cargo/config
          key: "cargo-deps-${{ hashFiles('**/Cargo.lock') }}"
      - name: "Vendor dependecies"
        if: steps.cache-cargo-vendor.outputs.cache-hit != 'true'
        shell: bash
        run: "cargo vendor --locked --versioned-dirs >> .cargo/config"
      - name: "Install System Deps"
        shell: bash
        run: "env CI=yes PATH=$PATH ./get-deps"
      - name: "Build wezterm (Release mode)"
        shell: bash
        run: "cargo build -p wezterm --release"
      - name: "Build wezterm-gui (Release mode)"
        shell: bash
        run: "cargo build -p wezterm-gui --release"
      - name: "Build wezterm-mux-server (Release mode)"
        shell: bash
        run: "cargo build -p wezterm-mux-server --release"
      - name: "Upload artifact"
        uses: actions/upload-artifact@v4
        with:
          name: "patched-ubuntu22.04"
          path: |
            target/release/wezterm
            target/release/wezterm-gui
            target/release/wezterm-mux-server
          retention-days: 30
