name: Nix / Build

on:
  pull_request:
    branches:
      - main
    paths:
      - '**/*.rs'
      - '.github/workflows/nix.yml'
      - 'nix/**'
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '**/*.rs'
      - '.github/workflows/nix.yml'
      - 'nix/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Install nix
        uses: DeterminateSystems/determinate-nix-action@v3.21.1

      - name: Cache build artifacts
        uses: DeterminateSystems/flakehub-cache-action@v3

      - name: Check flake inputs
        # note: waiting for a release with node24 upgrade
        # see: https://github.com/DeterminateSystems/flake-checker-action/pull/110
        uses: DeterminateSystems/flake-checker-action@main
        with:
          flake-lock-path: ./nix/flake.lock
          ignore-missing-flake-lock: false

      - name: Build default package
        run: nix build ./nix
